# Generated by Django 5.0.1 on 2024-01-04 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_number',
        ),
    ]
