# Generated by Django 5.0.1 on 2024-01-05 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_item_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='created_at',
            new_name='date',
        ),
    ]
