# Generated by Django 5.0.1 on 2024-01-04 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0005_rename_created_at_item_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemimage',
            old_name='image',
            new_name='src',
        ),
    ]
