# Generated by Django 5.0.1 on 2024-01-10 07:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0009_alter_feedback_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='customer_name',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback_text',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='rating',
        ),
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.EmailField(default='no-reply@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='rate',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
