# Generated by Django 5.0.1 on 2024-01-12 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0014_rename_orderitem_basket_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_address',
        ),
    ]
