# Generated by Django 5.0.1 on 2024-01-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0015_remove_order_delivery_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('Online', 'online'), ('Credit', 'credit'), ('Cash', 'cash')], max_length=20),
        ),
    ]
