# Generated by Django 5.0.1 on 2024-01-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0017_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('placing', 'placing'), ('in process', 'in process'), ('archived', 'Archived')], default='active', max_length=10),
        ),
    ]
