# Generated by Django 5.0.1 on 2024-01-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0018_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=10000, editable=False, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('Online', 'online'), ('Credit', 'credit'), ('Cash', 'cash')], default='Online', max_length=20),
        ),
    ]
