# Generated by Django 5.0.1 on 2024-01-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0022_order_delivery_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.CharField(choices=[('standard', 'Доставка'), ('express', 'Экспресс-доставка')], max_length=20)),
                ('express_delivery_fee', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
                ('free_delivery_threshold', models.DecimalField(decimal_places=2, default=2000, max_digits=10)),
                ('standard_delivery_fee', models.DecimalField(decimal_places=2, default=200, max_digits=10)),
            ],
        ),
    ]
