# Generated by Django 5.0.1 on 2024-01-19 06:49

import shopapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0023_deliverysettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to=shopapp.models.category_preview_directory_path),
        ),
    ]
