# Generated by Django 5.0.1 on 2024-01-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0028_alter_deliverysettings_delivery_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('ordinary', 'ordinary'), ('express', 'express')], default='standard', max_length=20),
        ),
    ]
