# Generated by Django 5.0.1 on 2024-01-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0029_alter_order_delivery_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('pending', 'pending'), ('delivery', 'delivery'), ('payment', 'payment'), ('archived', 'Archived')], default='active', max_length=10),
        ),
    ]
