# Generated by Django 5.0.1 on 2024-01-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0033_alter_sale_date_from_alter_sale_date_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='items',
            field=models.ManyToManyField(through='shopapp.SaleItem', to='shopapp.item'),
        ),
    ]
