# Generated by Django 5.0.1 on 2024-01-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0002_rename_phone_number_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
